language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t carlmeyrick/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carlmeyrick/docker-react npm run test